export const AppImages = {
  Welcome: require('./welcome.png'),
  OnBoarding1: require('./onboarding1.png'),
  OnBoarding2: require('./onboarding2.png'),
  OnBoarding3: require('./onboarding3.png'),
  Apple: require('./Apple.png'),
  Google: require('./Google.png'),
  FaceBook: require('./Facebook.png'),
  Back: require('./Back.png'),
  Email: require('./email.png'),
  Visibility: require('./visibility.png'),
  VisibilityOff: require('./visibility_off.png'),
  Success: require('./Success.png'),
  Menu: require('./Menu.png'),
  Notification: require('./Notification.png'),
  Women: require('./Women.png'),
  Men: require('./Men.png'),
  Accessories: require('./Accessories.png'),
  Beauty: require('./Beauty.png'),
  Background1: require('./background1.jpg'),
  LinenDress: require('./LinenDress.png'),
  NotFav: require('./NotFav.png'),
  Fav: require('./Fav.png'),
};
